# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  global:
    - R_LIBS_USER=~/R
  matrix:
    - TARGET=travis
    - TARGET=integration EXTRA_INSTALL_INSTRUCTIONS="sudo apt-get install --no-install-recommends qpdf texinfo texlive-latex-recommended texlive-latex-extra lmodern texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils"

# install dependencies
install:
  - echo "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
      | sudo tee /etc/apt/sources.list.d/cran.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/cran.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-c2d4u-precise.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-get install r-base-dev r-cran-xml r-cran-rcurl r-cran-rgl r-recommended
  - ${EXTRA_INSTALL_INSTRUCTIONS}
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages("knitr", dep = TRUE, repos = c("http://rforge.net", "http://cran.rstudio.org"))'

# run tests
script:
  - make ${TARGET}

# run check against R-devel
after_script:
  - if [ ${TARGET} = travis ]; then sudo add-apt-repository -y ppa:marutter/rdev; fi
  - if [ ${TARGET} = travis ]; then sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-rdev-precise.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"; fi
  - if [ ${TARGET} = travis ]; then sudo apt-get dist-upgrade; fi
  - if [ ${TARGET} = travis ]; then make ${TARGET}; fi
