# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  global:
    - R_LIBS_USER=~/R
  matrix:
    - TARGET=travis
    - TARGET=integration INSTALL_LATEX=T INSTALL_DVISVGM=T INSTALL_XPRA=T DISPLAY=:8

# capturing state
before_install:
  - env | sort

# install dependencies
install:
  - echo "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
      | sudo tee /etc/apt/sources.list.d/cran.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/cran.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/marutter-c2d4u-precise.list"
      -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-get install r-base-dev r-cran-xml r-cran-rcurl r-cran-rgl r-recommended
  - if [ -n "${INSTALL_LATEX}" ];
      then
        sudo apt-get install --no-install-recommends qpdf texinfo
          texlive-latex-recommended texlive-latex-extra lmodern
          texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils;
      fi
  - if [ -n "${INSTALL_DVISVGM}" ];
      then
        sudo apt-add-repository -y ppa:martin-gieseking/ppa;
        sudo apt-get update
          -o Dir::Etc::sourcelist="sources.list.d/martin-gieseking-ppa-precise.list"
          -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0";
        sudo apt-get install dvisvgm;
      fi
  - if [ -n "${INSTALL_XPRA}" ]; then curl http://winswitch.org/gpg.asc | sudo apt-key add - ; fi
  - if [ -n "${INSTALL_XPRA}" ]; then echo "deb http://winswitch.org/ `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/winswitch.list; fi
  - if [ -n "${INSTALL_XPRA}" ]; then sudo apt-get update; fi
  - if [ -n "${INSTALL_XPRA}" ]; then sudo apt-get install xpra; fi
  - if [ -n "${INSTALL_XPRA}" ]; then xpra start $DISPLAY; fi
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages("knitr", dep = TRUE, repos = c("http://rforge.net", "http://cran.rstudio.org"))'

# run tests
script:
  - make ${TARGET}

# run check against R-devel
after_script:
  - if [ ${TARGET} = travis ];
      then
        sudo add-apt-repository -y ppa:marutter/rdev;
    fi
  - if [ ${TARGET} = travis ];
      then
        sudo apt-get update
          -o Dir::Etc::sourcelist="sources.list.d/marutter-rdev-precise.list"
          -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0";
      fi
  - if [ ${TARGET} = travis ]; then sudo apt-get dist-upgrade; fi
  - if [ ${TARGET} = travis ]; then make ${TARGET}; fi
